# backend/safety/constants.py
from django.db import models

RULE_ENGINE_VERSION = "1.0.0"
MIN_SAFETY_CONFIDENCE = 0.70

class RiskLevel(models.TextChoices):
    SAFE = "SAFE", "SAFE"
    LOW = "LOW", "LOW"
    MEDIUM = "MEDIUM", "MEDIUM"
    HIGH = "HIGH", "HIGH"
    CRITICAL = "CRITICAL", "CRITICAL"

class SafetyStatus(models.TextChoices):
    PENDING = "PENDING", "PENDING"
    ANALYZING = "ANALYZING", "ANALYZING"
    APPROVED = "APPROVED", "APPROVED"
    BLOCKED = "BLOCKED", "BLOCKED"
    FAILED = "FAILED", "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED", "REVIEW_REQUIRED"

class HazardCategory(models.TextChoices):
    BATTERY = "BATTERY", "BATTERY"
    LITHIUM_BATTERY = "LITHIUM_BATTERY", "LITHIUM_BATTERY"
    CHEMICAL = "CHEMICAL", "CHEMICAL"
    TOXIC = "TOXIC", "TOXIC"
    MEDICAL = "MEDICAL", "MEDICAL"
    BIOHAZARD = "BIOHAZARD", "BIOHAZARD"
    SHARP_OBJECT = "SHARP_OBJECT", "SHARP_OBJECT"
    E_WASTE = "E_WASTE", "E_WASTE"
    PRESSURIZED_CONTAINER = "PRESSURIZED_CONTAINER", "PRESSURIZED_CONTAINER"
    FLAMMABLE = "FLAMMABLE", "FLAMMABLE"
    CORROSIVE = "CORROSIVE", "CORROSIVE"
    UNKNOWN = "UNKNOWN", "UNKNOWN"

class DecisionSource(models.TextChoices):
    RULE_ENGINE = "RULE_ENGINE", "RULE_ENGINE"
    AI_MODEL = "AI_MODEL", "AI_MODEL"
    RULE_OVERRIDE = "RULE_OVERRIDE", "RULE_OVERRIDE"
    MANUAL_REVIEW = "MANUAL_REVIEW", "MANUAL_REVIEW"

class ReviewPriority(models.TextChoices):
    LOW = "LOW", "LOW"
    MEDIUM = "MEDIUM", "MEDIUM"
    HIGH = "HIGH", "HIGH"
    CRITICAL = "CRITICAL", "CRITICAL"

class ReviewStatus(models.TextChoices):
    OPEN = "OPEN", "OPEN"
    IN_PROGRESS = "IN_PROGRESS", "IN_PROGRESS"
    RESOLVED = "RESOLVED", "RESOLVED"
    REJECTED = "REJECTED", "REJECTED"
