# Generated by Django 5.0 on 2026-06-01 19:59
import uuid
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=512)),
                ('image_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ANALYZING', 'Analyzing'), ('PENDING_CONFIRMATION', 'Pending Confirmation'), ('PENDING_CLARIFICATION', 'Pending Clarification'), ('CLASSIFIED', 'Classified'), ('FAILED', 'Failed')], default='ANALYZING', db_index=True, max_length=30)),
                ('predicted_category', models.CharField(blank=True, choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Glass', 'Glass'), ('Metal', 'Metal'), ('Organic', 'Organic'), ('Textile', 'Textile'), ('E-Waste', 'E-Waste'), ('Hazardous', 'Hazardous'), ('Mixed Waste', 'Mixed Waste')], db_index=True, max_length=50, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, db_index=True, max_digits=5, null=True)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('clarification_questions', models.JSONField(blank=True, default=list)),
                ('disposal_instructions', models.TextField(blank=True, null=True)),
                ('upcycling_guides', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['citizen', 'status'], name='classificat_citizen_idx'),
                    models.Index(fields=['image_sha256', 'status'], name='classificat_image_sha_idx'),
                ],
            },
        ),
    ]
