# Generated by Django 5.2.14 on 2026-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wasteitem',
            new_name='classificat_citizen_946793_idx',
            old_name='classificat_citizen_idx',
        ),
        migrations.RenameIndex(
            model_name='wasteitem',
            new_name='classificat_image_s_a75755_idx',
            old_name='classificat_image_sha_idx',
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='confidence_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=5, max_length=5, null=True),
        ),
    ]
