# Generated by Django 5.2.15 on 2026-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_rename_classificat_citizen_idx_classificat_citizen_946793_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='confidence_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
