# Generated by Django 5.2.14 on 2026-06-01 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0002_rename_classificat_citizen_idx_classificat_citizen_946793_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ANALYZING', 'ANALYZING'), ('APPROVED', 'APPROVED'), ('BLOCKED', 'BLOCKED'), ('FAILED', 'FAILED'), ('REVIEW_REQUIRED', 'REVIEW_REQUIRED')], db_index=True, default='PENDING', max_length=32)),
                ('risk_level', models.CharField(choices=[('SAFE', 'SAFE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], db_index=True, default='SAFE', max_length=32)),
                ('risk_score', models.FloatField(default=0.0)),
                ('decision_source', models.CharField(choices=[('RULE_ENGINE', 'RULE_ENGINE'), ('AI_MODEL', 'AI_MODEL'), ('RULE_OVERRIDE', 'RULE_OVERRIDE'), ('MANUAL_REVIEW', 'MANUAL_REVIEW')], db_index=True, default='AI_MODEL', max_length=32)),
                ('hazard_categories', models.JSONField(blank=True, default=list)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('safe_disposal_method', models.TextField(blank=True, default='')),
                ('approved_upcycling', models.JSONField(blank=True, default=list)),
                ('blocked_upcycling', models.JSONField(blank=True, default=list)),
                ('review_required', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True, default='')),
                ('rule_engine_version', models.CharField(default='1.0.0', max_length=32)),
                ('model_version', models.CharField(default='gemini-1.5-flash', max_length=64)),
                ('assessment_version', models.CharField(db_index=True, default='1.0.0:gemini-1.5-flash', max_length=128)),
                ('processing_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_item', models.OneToOneField(help_text='One-to-one mapping to the classification WasteItem.', on_delete=django.db.models.deletion.CASCADE, related_name='safety_assessment', to='classification.wasteitem')),
            ],
        ),
        migrations.CreateModel(
            name='ManualSafetyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('REJECTED', 'REJECTED')], default='OPEN', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', max_length=32)),
                ('sla_due_at', models.DateTimeField()),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_safety_reviews', to=settings.AUTH_USER_MODEL)),
                ('waste_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_safety_reviews', to='classification.wasteitem')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reviews', to='safety.safetyassessment')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_uri', models.CharField(help_text='URI pointing to the compressed GCS payload.', max_length=512)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('decision', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('waste_item', models.ForeignKey(help_text='Immutable log entry representing audit trails.', on_delete=django.db.models.deletion.PROTECT, related_name='safety_audit_logs', to='classification.wasteitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='safetyassessment',
            index=models.Index(fields=['status', 'created_at'], name='safety_safe_status_cd9951_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyassessment',
            index=models.Index(fields=['risk_level', 'created_at'], name='safety_safe_risk_le_ffa8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyassessment',
            index=models.Index(fields=['decision_source', 'created_at'], name='safety_safe_decisio_fd92c0_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyassessment',
            index=models.Index(fields=['processing_token'], name='safety_safe_process_e05dda_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetyassessment',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__gte', 0.0), ('risk_score__lte', 1.0)), name='valid_risk_score'),
        ),
        migrations.AddIndex(
            model_name='manualsafetyreview',
            index=models.Index(fields=['status', 'priority'], name='safety_manu_status_1c8ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='manualsafetyreview',
            index=models.Index(fields=['sla_due_at'], name='safety_manu_sla_due_886901_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyauditlog',
            index=models.Index(fields=['payload_hash'], name='safety_safe_payload_0b272f_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyauditlog',
            index=models.Index(fields=['created_at'], name='safety_safe_created_ff304c_idx'),
        ),
    ]
