# Generated by Django 5.2.15 on 2026-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
